controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_list:
    path: /list
    controller: App\Controller\ShoppingListController::index

app_home:
    path: /
    controller: App\Controller\ShoppingListController::index

app_set_pseudo:
    path: /set_pseudo
    controller: App\Controller\PseudoController::set_pseudo

app_logout:
    path: /logout

app_admin:
    path: /admin
    controller: App\Controller\AdminController::index

app_admin_product_add:
    path: /admin/product
    controller: App\Controller\ProductController::index

app_admin_product_category:
    path: /admin/category
    controller: App\Controller\CategoryController::index

